package main

import (
	"context"
	"log"

	pb "github.com/repodevs/shippy-service-consignment/proto/consignment"
	vesselProto "github.com/repodevs/shippy-service-vessel/proto/vessel"

	"github.com/micro/go-micro/v2"
)

type repository interface {
	Create(*pb.Consignment) (*pb.Consignment, error) 
	GetAll() []*pb.Consignment
}

// Repository - Dummy repository for datastore
// replace with real implementation later on.
type Repository struct {
	consignments	[]*pb.Consignment
}

// Create a new consignment
func (repo *Repository) Create(cm *pb.Consignment) (*pb.Consignment, error) {
	updated := append(repo.consignments, cm)
	repo.consignments = updated
	return cm, nil
}

// GetAll consignments
func (repo *Repository) GetAll() []*pb.Consignment {
	return repo.consignments
}

// service defined all method thas generated by protobuff
type consignmentService struct {
	repo repository
	vesselClient vesselProto.VesselService
}

// CreateConsignment ...
func (s *consignmentService) CreateConsignment(ctx context.Context, req *pb.Consignment, res *pb.Response) error {
	// Call client instance of vessel service
	vesselResp, err := s.vesselClient.FindAvailable(context.Background(), &vesselProto.Specification{
		MaxWeight: req.Weight,
		Capacity: int32(len(req.Containers)),
	})
	if err != nil {
		return err
	}
	log.Printf("Found vessel: %s", vesselResp.Vessel.Name)

	// Set VesselId based from vessel client
	req.VesselId = vesselResp.Vessel.Id

	// Create consignment
	consignment, err := s.repo.Create(req)
	if err != nil {
		return err
	}

	res.Created = true
	res.Consignment = consignment
	return nil
}

// GetConsignments ...
func (s *consignmentService) GetConsignments(ctx context.Context, req *pb.GetRequest, res *pb.Response) error {
	consignments := s.repo.GetAll()
	res.Consignments = consignments
	return nil
}


func main() {
	repo := &Repository{}

	// Create Micro Service
	service := micro.NewService(
		micro.Name("shippy.service.consignment"),
	)

	// Vessel client
	vesselClient := vesselProto.NewVesselService("shippy.service.vessel", service.Client())

	// init service
	service.Init()

	// Register service
	if err := pb.RegisterShippingServiceHandler(service.Server(), &consignmentService{repo, vesselClient}); err != nil {
		log.Panic(err)
	}

	// Run the server
	if err := service.Run(); err != nil {
		log.Panic(err)
	}
}